### ISSUE TITLE
Cloud not responding  (error: 404)

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.cloud#2]
Could you please make sure the cloud service is up an runnig?
It seems the link is not working anymore.

```
23:50:04.354 [EventThread] INFO  o.o.b.a.c.SocketWrapper Socket of user[e9df6579-d1d9-4a8c-a24d-af93d0024e9a] connected
23:50:04.866 [EventThread] INFO  o.o.b.a.c.SocketWrapper Logged in [e9df6579-d1d9-4a8c-a24d-af93d0024e9a] successfully
23:50:05.136 [EventThread] WARN  o.o.b.a.c.SocketWrapper Could not perform sync for user[e9df6579-d1d9-4a8c-a24d-af93d0024e9a]: "404: Requested entity was not found."
```

let me know if you need a detailed stack trace.

**Comment by DivineThreepwood** [comment]
ok, after removing and adding the bco google activity it seems to work again. At least the initial sync is fully performed.

**Comment by pLeminoq** [comment]
If the initial sync is performed then the cloud has to be up and running. I think you found the issue yourself which is that our google activity is used in testing mode which gets deactivated after a while.
